######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 3 17:37:36 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ttt.h ttt_board.h ttt_button.h
SOURCES += main.cpp ttt.cpp ttt_board.cpp ttt_button.cpp
