######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 3 16:58:08 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += hammer.h knee.h
SOURCES += reflex.cpp
